[package]
name = "engine_core"
version.workspace = true
edition.workspace = true

[dependencies]
glam.workspace = true
bytemuck.workspace = true
hecs.workspace = true
log.workspace = true
anyhow.workspace = true
thiserror.workspace = true
